{{- if .Values.apiclarity.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "apiclarity.name" . }}
  labels:
    {{ include "apiclarity.labels" . }}
rules:
- apiGroups: [""]
  resources: ["nodes", "services", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["replicasets", "daemonsets", "deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: [ "batch" ]
  resources: [ "jobs" ]
  verbs: [ "create", "get", "delete" ]
{{- end -}}
