apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apiclarity.name" . }}-fuzzer-template
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "apiclarity.labels" . }}
data:
  config: |-
    apiVersion: batch/v1
    kind: Job
    metadata:
      namespace: '{{ .Release.Namespace }}'
      labels:
{{- toYaml .Values.APIClarityRuntimeFuzzing.labels | nindent 8 }}
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 300
      template:
        metadata:
          labels:
{{- toYaml .Values.APIClarityRuntimeFuzzing.labels | nindent 12 }}
        spec:
          restartPolicy: Never
          volumes:
          - name: tmp-volume
            emptyDir: {}
          {{- if .Values.apiclarity.tls.enabled }}
          - name: root-ca
            configMap:
              name: {{ .Values.apiclarity.tls.rootCACertConfigMapName }}
          {{- end }}
          containers:
          - name: fuzzer
            image: "{{ .Values.APIClarityRuntimeFuzzing.docker.image }}"
            imagePullPolicy: Always
            volumeMounts:
              - mountPath: /tmp
                name: tmp-volume
              {{- if .Values.apiclarity.tls.enabled }}
              - name: root-ca
                mountPath: /etc/root-ca
                readOnly: true
              {{- end }}
            env:
            - name: PLATFORM_TYPE
              value: "API_CLARITY"
            {{- if .Values.apiclarity.tls.enabled }}
            - name: PLATFORM_HOST
              value: https://{{ include "apiclarity.name" . }}.{{ .Release.Namespace }}:8443/api
            {{- else }}
            - name: PLATFORM_HOST
              value: http://{{ include "apiclarity.name" . }}.{{ .Release.Namespace }}:8080/api
            {{- end }}
            - name: FUZZER
              value: "{{ .Values.APIClarityRuntimeFuzzing.methods }}"
            - name: RESTLER_ROOT_PATH
              value: "{{ .Values.APIClarityRuntimeFuzzing.restlerRootPath }}"
            - name: RESTLER_TOKEN_INJECTOR_PATH
              value: "{{ .Values.APIClarityRuntimeFuzzing.restlerTokenInjPath }}"
            - name: DEBUG
              value: "{{ .Values.APIClarityRuntimeFuzzing.debug }}"
            securityContext:
              capabilities:
                drop:
                - all
              runAsNonRoot: true
              runAsGroup: 1001
              runAsUser: 1001
              privileged: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
            resources:
{{- toYaml .Values.APIClarityRuntimeFuzzing.resources | nindent 14 }}
