{{- if .Values.apiclarity.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "apiclarity.name" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "apiclarity.labels" . }}
rules:
  # needed for trace sampling manger & fuzzer
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "delete"]
  # needed for fuzzer
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]

{{- end -}}
