apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: {{ .Values.global.databaseName }}
  POSTGRES_USER: {{ .Values.global.databaseUsername }}
  POSTGRES_PASSWORD: {{ .Values.global.databasePassword }}
