{{- if .Values.trafficSource.tap.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
  name: {{ include "apiclarity-taper.name" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "apiclarity-taper.labels" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "apiclarity-taper.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "apiclarity-taper.name" . }}
    spec:
      serviceAccountName: {{ include "apiclarity-taper.name" . }}
      containers:
        - command:
            - ./agent
            - -i
            - any
            - --log-level
            - {{ .Values.trafficSource.tap.logLevel }}
          env:
            - name: GOGC
              value: "12800"
            {{- if .Values.apiclarity.tls.enabled }}
            - name: UPSTREAM_TELEMETRY_HOST_NAME
              value: '{{ include "apiclarity.name" . }}.{{ .Release.Namespace }}:9443'
            {{- else }}
            - name: UPSTREAM_TELEMETRY_HOST_NAME
              value: '{{ include "apiclarity.name" . }}.{{ .Release.Namespace }}:9000'
            {{- end }}
            - name: TRACE_SAMPLING_HOST_NAME
              value: '{{ include "apiclarity.name" . }}.{{ .Release.Namespace }}:9990'
            - name: TRACE_SAMPLING_ENABLED
              value: "{{ .Values.global.traceSampling.enable }}"
            - name: NAMESPACES_TO_TAP
              value: {{ join " " .Values.trafficSource.tap.namespaces }}
            {{- if .Values.apiclarity.tls.enabled }}
            - name: ENABLE_TLS
              value: "{{ .Values.apiclarity.tls.enabled }}"
            - name: ROOT_CERT_FILE_PATH
              value: /etc/root-ca/{{ .Values.apiclarity.tls.rootCertFileName }}
            {{- end }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          image: '{{ .Values.global.docker.registry }}/passive-taper:{{ .Values.trafficSource.tap.docker.imageTag }}'
          imagePullPolicy: {{ .Values.trafficSource.tap.docker.imagePullPolicy }}
          name: apiclarity-taper
          resources:
            limits:
              cpu: 750m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 50Mi
          securityContext:
            privileged: true
          volumeMounts:
            {{- if .Values.apiclarity.tls.enabled }}
            - name: root-ca
              mountPath: /etc/root-ca
              readOnly: true
            {{- end }}
      volumes:
      {{- if .Values.apiclarity.tls.enabled }}
      - name: root-ca
        configMap:
          name: {{ .Values.apiclarity.tls.rootCACertConfigMapName }}
      {{- end }}
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
{{- end }}
