{{- if .Values.trafficSource.tap.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "apiclarity-taper.name" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "apiclarity-taper.labels" . }}
{{- end }}
